default: &default
  adapter: postgresql
  pool: 5
  encoding: utf8
  username: bogdan

development:
  <<: *default
  database: proziceri_dev

test:
  <<: *default
  database: proziceri_test

production:
  <<: *default
  database: proziceri_prod
