# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9814c2b2ea3dc5c78bfe7800620a7ebbbb6bf9fd74077ceaab40cd23a24fa8d1e646899a86164742e2d61bc6cc9c403fb526065a057d6ed16bb196d6934b443e

test:
  secret_key_base: 9f014a0e452ca2b81edc1b94f53f464b395dc26fc5e7c0137f757c4a19552a07684c59468fa593f31af7efb6e3dedb7d0cb368c32574caeb33434f0c1e84ae70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
